### PR TITLE
removed '-' as it's not a graphite forbidden char

### PR DESCRIPTION
**Pull request by NicoAdrian**

### CODE REVIEW

**Comment by Shir0kamii** [comment]
That's a good catch, thank you for the contribution!

**Comment by NicoAdrian** [comment]
I don't know how that works but could you "push" master to Pypi please ? When I install it via pip, I don't get the new changes
thanks

**Comment by Shir0kamii** [comment]
I'd like to add a few more things before publishing a new release on Pypi.

You should be able to use this command to install the master version:

```bash
pip install git+git://github.com/Shir0kamii/graphitesender.git#egg=graphitesender
```

If this solution is not applicable in your setting, please tell me, I'll still make a release.

**Comment by NicoAdrian** [comment]
Yea it works like that but I use SaltStack to deploy my project and if I put this line:
`git+git://github.com/Shir0kamii/graphitesender.git#egg=graphitesender`
in requirements.txt, Salt doesn't run it with my proxy so the command fails... 
So a Pypi release would be great :D

**Comment by Shir0kamii** [comment]
I just released the version 0.11.1, enjoy!

**Pull request merged**
